services:
  haredev:
    build:
      context: .
      dockerfile: Dockerfile
    image: hare-dev:latest
    platform: linux/amd64
    container_name: haredev
    working_dir: /workspace
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
